action_endpoint:
#  url: "http://172.18.86.21:5055/webhook"
  url: "http://172.18.86.21:5055/api/action"
#   url: http://47.103.73.160:5055/webhook


#Tracker Store
tracker_store:
    type: mongod
    url: mongodb://172.18.86.20:27017/
    db: "chatbot"
    username: ''
    password: ''
    auth_source: "chatbot_CN"


# Tracker Store Redis  test

#tracker_store:
#    type: mongod
#    url: mongodb://47.103.73.160:27017/
#    db: "chatbot"
#    username: 'chatbot'
#    password: '123456'
#    auth_source: "admin"