action_endpoint:
#  url: "http://172.16.19.74:5055/webhook"
   url: http://172.18.86.21:5055/webhook


#Tracker Store
tracker_store:
    type: mongod
    url: mongodb://172.18.86.20:27017/
    db: "chatbot"
    username: ''
    password: ''
    auth_source: "cuishou_bot"